### ISSUE TITLE
Link in placeholder readme area broken?

### ISSUE THREAD

**Issue by steakwipe** [Penumbra-Sync/client#2]
Perhaps just on my end but trying to hit the link for the repo to add, fires up discord in a new tab and doesn't seem to actually load a server. Possibly 'cause it's a channel link to a server I'm not in, unsure, discord is .. discord.

Could we get a clarified or updated link to the discord server or Dalamud repo in question? Or if it really is just some problem on my end, we can shame my computer too. 😋

Sorry to bother, this is just a very exciting project! Thanks :)

**Comment by rootdarkarchon** [comment]
Resolved
