### ISSUE TITLE
Suggestion: log to own log file rather than Dalamud's

### ISSUE THREAD

**Issue by Limiana** [Penumbra-Sync/client#47]
I would like to suggest to consider making your own logging, separate from Dalamud's log file. It's really painful to work with people's logs who have Mare Synchronous installed... out of 6k lines, 4k belong to it and all go into informational or higher channels.

**Comment by rootdarkarchon** [comment]
Mares logging is intentionally using separate internal log levels. People just leave it on trace or debug for no good reason instead of setting it back.

**Comment by rootdarkarchon** [comment]
I will add a warning on startup if the log level is set to anything lower than `Informational` for 0.8.0 so people don't leave it on that level.

**Comment by rootdarkarchon** [comment]
In the meantime, Visual Studio code Regex Replace `^.*\[MareSynchronos\].*\n` to empty string will remove all Mare log lines.

**Comment by rootdarkarchon** [comment]
https://github.com/Penumbra-Sync/client/commit/3e1ddca88c96b476f373ab6117c9b1db8159afd1
