### ISSUE TITLE
Game crash when transforming in to a monster model

### ISSUE THREAD

**Issue by syldrathecat** [Penumbra-Sync/client#59]
The plugin seems to cause the game to almost always crash and immediately exit if your character is transformed in to a non-Human model. This **only seems to occur on non-Windows platforms**, for some reason. I believe it is due to invalid memory accesses.

I've experienced crashes in at least the following situations:

 * Transforming to a gorilla/bird in Fist of the Son
 * Mounting a robot in Rival Wings
 * Being turned in to a creature by a White Mage's Miracle of Nature in PvP
 * Being turned in to a creature by A Rank Mahisha in The Peaks

Some relevant lines are logged immediately before a crash:

```
[INF] [MareSynchronos] [Player...actory]{0} Checking File Replacement for Model chara/monster/m0216/obj/body/b0002/model/m0216b0002.mdl
[...]
[INF] [MareSynchronos] [Player...actory]{0} Checking skeleton chara/human/c49472/skeleton/base/b0001/skl_c49472b0001.sklb
```
^ Transformed in to a monster model. The race id 49472 is nonsense and something random each time.

```
[WRN] [MareSynchronos] [Player...actory]{3} Could not get Decal data: 

[WRN] [MareSynchronos] [Player...actory]{3} Could not get Legacy Body Decal Data: 
```
^ these indicate that there is an issue accessing the player's GameObject as a Human* when it is no longer a Human.

```
[INF] [MareSynchronos] [Player...actory]{0} Checking File Replacement for Texture H�l$H�t$H�|$ AVH�� H�D$XI��I��L��H�����u�AX����D�`H�\$0=V
```
^ Lines like this are occasionally logged as well

```
[INF] [MareSynchronos] [Player...actory]{1} Glamourer is now: [...]
[INF] [MareSynchronos] [Player...actory]{1} Customize is now: [...]
```
^ These are the final lines logged before the game closes. Palette+ is installed.

Adding this check to CreateCharacterData() seems to avoid the crash, but I don't know if its ideal (might affect someone using monster model mods?):

```patch
diff --git a/MareSynchronos/PlayerData/Factories/PlayerDataFactory.cs b/MareSynchronos/PlayerData/Factories/PlayerDataFactory.cs
index d3a63fd..8dc2731 100644
--- a/MareSynchronos/PlayerData/Factories/PlayerDataFactory.cs
+++ b/MareSynchronos/PlayerData/Factories/PlayerDataFactory.cs
@@ -329,6 +329,24 @@ public class PlayerDataFactory
             totalWaitTime -= 50;
         }
 
+        if (objectKind == ObjectKind.Player)
+        {
+            bool inhuman = false;
+
+            unsafe
+            {
+                var drawObj = (DrawObject*)((Character*)charaPointer)->GameObject.GetDrawObject();
+                inhuman = (drawObj->Object.GetObjectType() == ObjectType.CharacterBase && ((CharacterBase*)drawObj)->GetModelType() != CharacterBase.ModelType.Human);
+            }
+
+            if (inhuman)
+            {
+                _logger.LogInformation("Skipping processing of character with non-Human model type");
+                return previousData;
+            }
+        }
+
+
         Stopwatch st = Stopwatch.StartNew();
 
         // gather static replacements from render model
```

When the character un-transforms it triggers another character check, so there's not any lasting effects here.

Also maybe interesting to know is Penumbra's "On-Screen" tab will fail with an AccessViolationException as well, while a player is transformed in to a monster:

![image](https://github.com/Penumbra-Sync/client/assets/13056379/ab32b271-f49e-43ee-8feb-564fa72e9131)

**Comment by rootdarkarchon** [comment]
As I'm going to switch to Penumbras in-house collection of materials, textures and models down the line this is something you should bring up with the Penumbra dev as that shares the same code with On-Screen.

**Comment by syldrathecat** [comment]
go fuck yourself

**Comment by blargle-ragequit** [comment]
I am still having this issue unfortunately.  Both with and without "Use Penumbra to resolve character" checked, being turned into a pig by a white mage in pvp and being turned into a frog by halicarnassus have crashed my game.
