### ISSUE TITLE
Mods not synchronizing after Patch 6.55

### ISSUE THREAD

**Issue by strikerttd** [Penumbra-Sync/client#68]
My friend and I have various mods installed. Before 6.55, we were able to see each other's custom mounts, dances, etc. After the patch and after Dalamud and Penumbra were updated, our mods no longer seem to be showing up for each other.

We have attempted to remove and re-add each other to the sync to no avail.

**Comment by Theo-Asterio** [comment]
> My friend and I have various mods installed. Before 6.55, we were able to see each other's custom mounts, dances, etc. After the patch and after Dalamud and Penumbra were updated, our mods no longer seem to be showing up for each other.
> 
> We have attempted to remove and re-add each other to the sync to no avail.

Please use the discord for support, this isn't nearly enough information to go on.
