### ISSUE TITLE
Mare crashes the game

### ISSUE THREAD

**Issue by Floki2k1** [Penumbra-Sync/client#8]
A friend of mine downloaded Mare and Glamourer. Though every time it trys to synch me and him it crashes his game.  
Edit: My friend is also from Chaos and I am from Light.
Another Edit: By testing around we found out that the game crashes when the mod of the other person is too big in size. Also it only crashes when I activate a mod that my friend doesn't have, but if he activates one that I don't have it downloads as normal.

**Comment by rootdarkarchon** [comment]
probably penumbra issue, update to latest, should be fine
